-- 기본 게시판 테이블
CREATE TABLE BASIC_BOARD (
	BOARD_NUM INT PRIMARY KEY
	, BOARD_TITLE VARCHAR(50) NOT NULL
	, BOARD_CONTENT VARCHAR(50)
	, WRITER VARCHAR(20) NOT NULL
	, CREATE_DATE VARCHAR(20) NOT NULL 
	, READ_CNT INT DEFAULT 0
);

SELECT *
FROM basic_board; 

-- UPDATE 문법
UPDATE basic_board
SET
WRITER = '김자바';
WHERE BOARD_NUM = 1;

UPDATE basic_board
SET
	WRITER = '홍자바';
	, BOARD_CONTENT = '변경내용'
WHERE BOARD_NUM = 1;

COMMIT;

-- USER, MANAGER, ADMIN
CREATE TABLE SECURITY_MEMBER(
	MEMBER_ID VARCHAR(50)PRIMARY KEY
	, MEMBER_NAME VARCHAR(50) NOT  NULL
	, MEMBER_PW VARCHAR(50) NOT NULL
	, MEMBER_ROLL VARCHAR(50) DEFAULT 'USER'
);

SELECT * FROM SECURITY_MEMBER;

SELECT * FROM BOARD;

DROP TABLE SECURITY_MEMBER;

DELETE FROM board;
