-- 기본키(PRIMARY KEY : PK)
-- NULL 이 들어갈수 없고, 테이블 내에서 중복 데이터 불가
-- 회원 정보 테이블
CREATE TABLE BOARD_MEMBER(
	-- 컬럼명, 자료형 [제약조건]
	MEMBER_ID VARCHAR(20) PRIMARY KEY
	, MEMBER_PW VARCHAR(20) NOT NULL
	, MEMBER_NAME VARCHAR(20) NOT NULL
	, GENDER VARCHAR(2) -- '남', '여'
	, MEMBER_EMAIL VARCHAR(30) NOT NULL UNIQUE -- NULL X , UNIQUE - 중복X
	, IS_ADMIN VARCHAR(2) DEFAULT 'N'-- 'N', 'Y'
);

-- 게시글 정보 테이블
DROP TABLE BOARD; -- 테이블 삭제
DELETE TABLE BOADR; -- 데이터만 삭제


-- WRITE : 외래키(Foreign key : Fk) 제약조건 
CREATE TABLE BOARD(
	BOARD_NUM INT AUTO_INCREMENT PRIMARY KEY
	, TITLE VARCHAR(30) NOT NULL
	, CONTENT VARCHAR(30)
	, WRITER VARCHAR(20) REFERENCES board_member (MEMBER_ID)
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP -- 게시글 작성 될때 날짜 및 시간
	, READ_CNT INT DEFAULT 0
);

CREATE TABLE BOARD_REPLY(
	REPLY_NUM INT AUTO_INCREMENT PRIMARY KEY
	, CONTENT VARCHAR(50) NOT NULL
	, CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, WRITER VARCHAR(20) REFERENCES board_member (MEMBER_ID)
	, BOARD_NUM INT REFERENCES board (BOARD_NUM)
);

SELECT *
FROM BOARD_REPLY;

SELECT NOW();

INSERT INTO BOARD (TITLE, CONTENT, WRITER)
VALUES ('AA', 'BB', NULL);

SELECT*
FROM board;

SELECT*
FROM board_member;

DELETE FROM board;

UPDATE board_member
SET
 IS_ADMIN = 'Y'
 WHERE MEMBER_ID ='admin';
 COMMIT;
 
 -- BOARD 테이블에서 제목에 java라는 글자가 포함된
-- 게시글의 모든 내용을 조회하는 쿼리.
-- 단, java라는 글자는 대,소문자 구분하지 않고 조회

SELECT*
FROM board;

SELECT TITLE
FROM board
WHERE TITLE LIKE '%java%';
 
SELECT CONCAT('aa')
