CREATE TABLE CAR_INFO( 
	MODEL_NUM INT AUTO_INCREMENT PRIMARY KEY
	, MODEL_NAME VARCHAR(10) NOT NULL
	, PRICE INT NOT NULL
	, MANUFACTURER VARCHAR(5) NOT NULL
);
SELECT * FROM car_info;
SELECT * FROM SALES_INFO;

CREATE TABLE SALES_INFO(
	SALE_NUM INT AUTO_INCREMENT PRIMARY KEY
	, PURCHASER VARCHAR(10) NOT NULL
	, PURCHASER_TEL VARCHAR(15)
	, COLOR VARCHAR(5) NOT NULL
	, SALE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, MODEL_NUM INT REFERENCES CAR_INFO (MODEL_NUM)
	);

DROP TABLE car_info;